### PR TITLE
Move tomschr/getentities to daps repo

### LINKED ISSUE #632: Avoiding repo sprawl because of Python components
So I'd already mentioned that I think this strategy of creating new repos for each of our small Python scripts and manually copying these scripts when need arises is a bit weird, and leads to blobby, barely reviewable commits which are rather less suitable for longer-term maintenance of DAPS. It also makes it harder to learn about where you should actually commit stuff into.

I think this issue could be resolved with a combination of symlinks + integrating the GHA workflows into the main `.github/workflows` dir:

```
daps
├── .github
│   ├── [issue template etc.]
│   └── workflows
│       ├── ci.yml
│       ├── python-xmlwellformed.yml
│       └── python-getentities.yml
├── python_scripts
│   ├── daps-xmlwellformed
│   │   └── [contents of the daps-xmlwellformed repo]
│   └── getentities
│       └── [contents of the getentities repo]
├── libexec
│   ├── daps-xmlwellformed --symlink--> ../python_scripts/daps-xmlwellformed/bin/daps-xmlwellformed.py
│   ├── getentities        --symlink--> ../python_scripts/getentities/bin/getentities.py
│   └── [other contents of the libexec/]
│
[... all the rest of the DAPS repo ...]
```

The remaining question would be how to package this -- imo the `python_scripts` dir should not be part of the RPM, rather we should resolve the symlinks from the `libexec` dir.

@tomschr / @fsundermeyer What do you think?

### PR DESCRIPTION
**Pull request by tomschr**
This PR tries to fix #632. It contains:

* Create link in `libexec`, points to `bin/getentityname.py`
* Add `.github/workflows/getentityname.yml` workflow file (only get activated when something below the path `python-scripts/getentityname/` has been changed.)

Related to #639

### CODE REVIEW

**Review by fsundermeyer — APPROVED** [review]
LGTM

**Comment by ghost** [comment]
The following comments apply to both this PR and #639 :

1. This may be a pipe dream -- but it would be great to import the history of the repo along with the files. Of course that is only possible when doing a `git format-patch` in the original repo, then fixing all paths to match new names in the generated patch files, and then importing those into the DAPS repo. I admit that is a bit of a time waster.
2. There may be typo fixes or other borderline useful changes in the files that are part of the DAPS repo -- I definitely know I applied a few comment typo fixes to `xml-wellformed.py`
3. I would prefer if these tools were not versioned independently of DAPS, would it be possible to either remove the version number entirely from these files or make sure to always use the DAPS version number?

**Comment by tomschr** [comment]
> 1. This may be a pipe dream -- but it would be great to import the history of the repo along with the files. [...]

In an ideal world, yes. However, I'm not sure if it is really incredibly important. The history isn't that meaningful. Additionally, as we have already a commit in main, adding commits from the past is a bit... weird, I guess?


> 2. There may be typo fixes or other borderline useful changes in the files that are part of the DAPS repo

We can add them of course. Where did you comment them? Not sure in this PR or in a new one.


> 3. I would prefer if these tools were not versioned independently of DAPS, would it be possible to either remove the version number entirely from these files or make sure to always use the DAPS version number?

Technically all possible.

Hmn, I'm not sure why you think this is such a problem. It make things more opaque **to me**. Although the version isn't really used nor shown to the user, it can carry important information in a debugging session. If we find a bug in one of these scripts, how do I know what version was executed if all version is the same (or none)?

Adding the DAPS version would work if we can assure consistency with DAPS. But is it worth the hassle?

Not sure what you are trying to fix. It wasn't broken before and I don't think it will be. Maybe I missed your point and we can discuss it in one of our upcoming calls.

**Comment by ghost** [comment]
> > 1. This may be a pipe dream -- but it would be great to import the history of the repo along with the files. [...]
> 
> In an ideal world, yes. However, I'm not sure if it is really incredibly important. The history isn't that meaningful. Additionally, as we have already a commit in main, adding commits from the past is a bit... weird, I guess?

Update: I have created replacement PRs for both scripts that include the full history (ok, lightly sanitized, but not much). And yes, it's a little weird to have commits from 2019 thrown into the middle of commits from 2021 but imo not too much. Having history is nice!


> > 1. There may be typo fixes or other borderline useful changes in the files that are part of the DAPS repo
> 
> We can add them of course. Where did you comment them? Not sure in this PR or in a new one.

I have added these fixes to the replacement PR: only daps-xmlwellformed had such fixes; getentityname was unchanged compared to upstream.


> > 1. I would prefer if these tools were not versioned independently of DAPS, would it be possible to either remove the version number entirely from these files or make sure to always use the DAPS version number?
> 
> Technically all possible.
> 
> Hmn, I'm not sure why you think this is such a problem. It make things more opaque **to me**. Although the version isn't really used nor shown to the user, it can carry important information in a debugging session. If we find a bug in one of these scripts, how do I know what version was executed if all version is the same (or none)?
> 
> Adding the DAPS version would work if we can assure consistency with DAPS. But is it worth the hassle?
> 
> Not sure what you are trying to fix. It wasn't broken before and I don't think it will be. Maybe I missed your point and we can discuss it in one of our upcoming calls.

I wouldn't block on the version number thing, but the reason why I think it is relevant is that it is a little confusing when each part of DAPS is showing a different version number. However, I do see your point that it's not ideal for debugging to have no version number at all.

**Comment by ghost** [comment]
Replaced by #649, which was merged instead.

The questions about version numbers are still open.

**Pull request closed without merging**
