### PR TITLE
Also detect our parameters STYLE.VERSION

### PR DESCRIPTION
**Pull request by tomschr**
@sknorr Please review. :)

Related to https://github.com/openSUSE/suse-xsl/pull/227

### CODE REVIEW

**Comment by ghost** [comment]
Hm, this will probably output something useless when both `fm:` and the `xsl:param` version are present... maybe add something like

```
<xsl:template match="/">
<xsl:choose>
<xsl:when test="descendant::fm:version">
  <xsl:apply-templates select="descendant::fm:version"/>
</xsl:when>
<xsl:when test="descendant::x:param[@name='STYLE.VERSION']">
  <xsl:apply-templates select="descendant::x:param[@name='STYLE.VERSION']"/>
</xsl:when>
<xsl:otherwise>NO_VERSION_FOUND</xsl:otherwise>
</xsl:choose>
</xsl:template>
```

Not sure if that is the best way of implementing it.

**Comment by tomschr** [comment]
Do we really have to? I mean, usually pass to the above stylesheet either the original **OR** our version file. But never both. Or do I miss something?

**Comment by ghost** [comment]
I think we should, yes, just as a matter of safety... What if the upstream stylesheets suddenly start shipping with a parameter that looks the same but has different semantics? (Yes, it is a little unlikely, but we should try to make sure that we get useful output regardless.)

**Comment by tomschr** [comment]
Hmn, ok, yes. As some precaution this could be useful. See commit a37ac17.

I took the freedom to slightly deviate from your original part. ;-) Oh, and by the way, you don't want to use the `descendant` axis here. I would consider it as highly dangerous.

**Comment by ghost** [comment]
Okay, let's merge... Thanks!

**Pull request merged**
