### PR TITLE
Remove old stuff: --jsp, online-docs, Ghostscript, and SVN stuff

### PR DESCRIPTION
**Pull request by ghost**
A day off is good for many things ... Be aware, this is basically all untested, though I tried to be correct.

### CODE REVIEW

**Review by tomschr — APPROVED** [review]
LGTM :gem:
Haven't found any issues so far.

**Comment by ghost** [comment]
@fsundermeyer I have updated the PR after yesterday's comments that the online-docs removal was not quite complete. The new changes are in an additional commit that I'll squash before merging.

**Review by fsundermeyer — APPROVED** [review]
LGTM - thank you very much!!

**Comment by ghost** [comment]
Thank you both for reviewing! Merged.

**Pull request merged**
