### PR TITLE
Adding fresh debian subdirectory

### PR DESCRIPTION
**Pull request by tbazant**

### CODE REVIEW

**Comment by fsundermeyer** [comment]
Thank you!

**Comment by lopippo** [comment]
Greetings,

I am the Debian package maintainer for daps. Could you tell me on which Debian distribution you test your package, please (unstable, testing, stable) ?

Thank you 
Filippo

**Comment by tbazant** [comment]
> Greetings,
> 
> I am the Debian package maintainer for daps. Could you tell me on which Debian distribution you test your package, please (unstable, testing, stable) ?
> 
> Thank you Filippo

Hi
i'm using it myself on Debian `testing` and used to use it on `stable` previously. Here is the build page for it https://build.opensuse.org/package/show/home:tbazant/daps

**Comment by lopippo** [comment]
Hi,
> Hi i'm using it myself on Debian `testing` and used to use it on `stable` previously. Here is the build page for it https://build.opensuse.org/package/show/home:tbazant/daps

Thanks.
Filippo

**Pull request merged**
