### PR TITLE
xmlformat config: Update config to work with new xmlformat version

### PR DESCRIPTION
**Pull request by ghost**
The default behavior of github.com/someth2say/xmlformat unfortunately no longer matches the default behavior of the previous Kitebird-xmlformat version.
Unfortunately, restoring the previous default behavior in the new version depends on a setting (`wrap-type`) that is not supported in Kitebird-xmlformat, and will lead to an error there.

Wondering a bit what to do here -- we could either 

1. Mandate the new version via an RPM recommends (xmlformat is _not a dependency_ of the package, from what I see, meaning we would not break DAPS in cases where xmlformat is not available in the requested version, which would most likely be relevant in OBS and for external contributors) or
2. We could keep two config files around for the time being and select the appropriate one with a version check (which is a little annoying to implement and seems more complicated than warranted.)

Relevant discussion with upstream at `https://github.com/someth2say/xmlformat/pull/13`.

### CODE REVIEW

**Review by tbazant — APPROVED** [review]
looks reasonable

**Comment by ghost** [comment]
@tbazant Is that a vote for option (1)?

**Comment by tbazant** [comment]
> @tbazant Is that a vote for option (1)?

After reading both discussions, yep, option 1 looks better to me.

**Review by fsundermeyer — CHANGES_REQUESTED** [review]
The change itself LGTM.

However, I strongly vote for option two unless upstream becomes compatible with Kitebird's config format. We do not know which xmlformat version will be used outside of SUSE. I am doing the same for the catalog files and the fop config files (see Makefile.am and configure.ac)

**Comment by ghost** [comment]
> unless upstream becomes compatible with Kitebird's config format.

Every unknown option in the config file leads to xmlformat exiting with an error. There's no way to make a single config file that is compatible with both tools and also works the same way across them.

**Comment by ghost** [comment]
@fsundermeyer As requested, I've added a version check which works sufficiently well in DAPS running from the repo (which I hope is sufficiently robust). There is still a mention of the old config file in `Makefile.am` (l. 145) that I dunno what to do with, `dist_dapsconf_DATA    = etc/config etc/docbook-xmlformat.conf \`. Please advise.

Also, arguably, line 36 in my current version is a bit superfluous, since the later `else` unconditionally sets the variable again. Again, please advise...

https://github.com/openSUSE/daps/blob/9be080d588124b3e7f6155db3f251dadd545ddc8/bin/daps-xmlformat.in#L36-L45

**Review by fsundermeyer — APPROVED** [review]
LGTM

**Comment by ghost** [comment]
Thanks all, merged!

**Pull request merged**
