### PR TITLE
Update the debian packaging work.

### PR DESCRIPTION
**Pull request by lopippo**
Seems to work fine on debian testing - next bookworm;

Greetings, Daps'istas,
as we were mentioning it some weeks ago, here is the debian directory for packaging daps for Debian. It seems to work fine  for me, but I only do ```DocBook -> HTML/PDF``` stuff, nothing epub or anything else. If you could check that, it would be superb:

```
# apt install daps
```

Sincerely, and keep the good work :-)
Filippo

### CODE REVIEW

**Comment by fsundermeyer** [comment]
@lopippo Tried to set up a VM with Debian bookworm (using the weekly snapshot of testing) and added the testing repo
`deb http://ftp.debian.org/debian testing main contrib non-free`
However, daps can't be found in that repository. Any ideas?

**Comment by lopippo** [comment]
Greetings, Frank,

On Tue, Nov 08, 2022 at 08:58:21AM -0800, Frank Sundermeyer wrote:
***@***.*** Tried to set up a VM with Debian bookworm (using the weekly snapshot of testing) and added the testing repo
>`deb http://ftp.debian.org/debian testing main contrib non-free`
>However, daps can't be found in that repository. Any ideas?

Please, try the following (mind the slash after 'debian'):

deb http://deb.debian.org/debian/ testing main 
or (same)
deb http://deb.debian.org/debian/ bookworm main

However, daps was removed from testing because of the xslt-related build failure
and it is now waiting to enter again after my last upload (3.3.2). My last check
tells me that the package will enter testing (bookworm) in 5 days or so.

Sincerely,
Filippo

-- 

⢀⣴⠾⠻⢶⣦⠀  Filippo Rusconi, PhD
⣾⠁⢠⠒⠀⣿⡁   Research scientist at CNRS
⢿⡄⠘⠷⠚⠋⠀   Debian Developer
⠈⠳⣄⠀⠀⠀⠀  http://msxpertsuite.org
           http://www.debian.org

~~~~
book: http://www.lavoisier.fr/livre/notice.asp?id=3LKW2OAR2KROWZ
http://books.google.fr/books?id=2NmguxmEI1sC&printsec=frontcover&dq=rusconi+f+lavoisier&hl=fr&sa=X&ei=nGGOUt2SH_Ly0gX0uIHoBQ&ved=0CDUQ6AEwAA#v=onepage&q&f=false
~~~~
Institut Diversité, Écologie et Évolution du Vivant
Unité Génétique Quantitative et Évolution
Plateforme PAPPSO

Université Paris-Saclay, INRAE, UMR CNRS 8120, AgroParisTech
12, route 128, Bâtiment 680
91272 Gif-sur-Yvette
France

http://moulon.inrae.fr/ & http://pappso.inrae.fr/
Tel : +33 (0)1 69 33 23 54
Fax : +33 (0)1 69 33 23 40

**Comment by ferdnyc** [comment]
Isn't this superseded by #730? Seems like it can be closed.

**Comment by fsundermeyer** [comment]
Thanks @ferdnyc , you are right. Closing

**Pull request closed without merging**
